### ISSUE TITLE
'Elm' refers to a UMD global typescript error in generated file

### ISSUE THREAD

**Issue by sebsheep** [dillonkearns/elm-ts-json#13]
The generated typescript file contains the following lines:

```ts
export as namespace Elm;

export { Elm };
```

which raises the following error when I try to build:
```
gen/mainBack.d.ts:36:10 - error TS2686: 'Elm' refers to a UMD global, but the current file is a module. Consider adding an import instead.

36 export { Elm };
            ~~~
```

removing this `export {Elm }` line makes Typescript happy.... Is it necessary to add this `export { Elm }` in the generated file? If yes, how could I solve this error and be able to build without performing a ugly `sed`?

**Comment by dillonkearns** [comment]
Elm uses UMD in its generated bundle. Removing that export line would not reflect the possible ways that UMD exports can be used (either as globals or with a require).

To make TypeScript stop warning about using UMD you can use this option: https://www.typescriptlang.org/tsconfig/#allowUmdGlobalAccess.
